language: csharp
solution: ExpressMapper.sln
install:
  - nuget restore ExpressMapper.sln
  - nuget install NUnit.Runners -Version 3.4.1 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release ExpressMapper.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.4.1/tools/nunit3-console.exe "./ExpressMapper.Tests/bin/Release/ExpressMapper.Tests.dll"
